// lib/config/supabase_config.dart
// Auto-generated by Glassbox — contains your Supabase credentials.
// DO NOT commit this file to a public repository.
abstract class SupabaseConfig {
  static const String url     = 'https://placeholder.supabase.co';
  static const String anonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.placeholder.placeholder';

  // Heuristic: real credentials look like "https://<ref>.supabase.co" + a
  // long JWT. The well-formed placeholders above will return false here so
  // the runtime can show a friendly "add Supabase credentials" toast on
  // any actual data call.
  static bool get isConfigured =>
    url.startsWith('https://') &&
    !url.contains('placeholder.supabase.co') &&
    anonKey.startsWith('eyJ') &&
    anonKey.length > 80;
}
