// lib/config/supabase_config.dart
// Auto-generated by Glassbox — contains your Supabase credentials.
// DO NOT commit this file to a public repository.
abstract class SupabaseConfig {
  static const String url     = 'https://ncdbndeojnjstkcpljhx.supabase.co';
  static const String anonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jZGJuZGVvam5qc3RrY3Bsamh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNzc1ODIsImV4cCI6MjA5MDY1MzU4Mn0.iW2n5uKw6tpkDiS1V_teHWrBz653XnXuIU_5fSpF9rI';
  static bool get isConfigured =>
    url.startsWith('https://') && anonKey.startsWith('eyJ');
}
