// lib/config/supabase_config.dart
// Auto-generated by Glassbox — contains your Supabase credentials.
// DO NOT commit this file to a public repository.
abstract class SupabaseConfig {
  static const String url     = 'YOUR_SUPABASE_URL';
  static const String anonKey = 'YOUR_SUPABASE_ANON_KEY';
  static bool get isConfigured =>
    url.startsWith('https://') && anonKey.startsWith('eyJ');
}
