// lib/utils/image_helper.dart
// Auto-generated by Flutter Builder — do not edit manually.
// Use these constants to reference imported images in your screens.
abstract class AppImages {
  AppImages._();

  static const String midjourney_aiart_aiartcommunity_animeart_animeartist_niji_digitalart_pokemon_a_1 = 'assets/images/midjourney_aiart_aiartcommunity_animeart_animeartist_niji_digitalart_pokemon_a_1.jpg';
  static const String img_1354791 = 'assets/images/img_1354791.jpeg';
}
