// lib/utils/image_helper.dart
// Auto-generated by Flutter Builder — do not edit manually.
// Use these constants to reference imported images in your screens.
abstract class AppImages {
  AppImages._();

  static const String loss_vs_iterations = 'assets/images/loss_vs_iterations.png';
  static const String midjourney_aiart_aiartcommunity_animeart = 'assets/images/midjourney_aiart_aiartcommunity_animeart.jpg';
  static const String midjourney_aiart_aiartcommunity_animeart_2 = 'assets/images/midjourney_aiart_aiartcommunity_animeart_2.jpg';
}
