// lib/utils/image_helper.dart
// Auto-generated by Flutter Builder — do not edit manually.
// Use these constants to reference imported images in your screens.
abstract class AppImages {
  AppImages._();

  static const String __________midjourney__aiart__aiartcommunity__animeart__animeartist__niji__digitalart__pokemon__a__3_ = 'assets/images/☁️ ..... #midjourney #aiart #aiartcommunity #animeart #animeartist #niji #digitalart #pokemon #a (3).jpg';
  static const String __________midjourney__aiart__aiartcommunity__animeart__animeartist__niji__digitalart__pokemon__a__2_ = 'assets/images/☁️ ..... #midjourney #aiart #aiartcommunity #animeart #animeartist #niji #digitalart #pokemon #a (2).jpg';
}
