// lib/utils/supabase_helper.dart
// Auto-generated by Glassbox — do not edit manually.
// Use this helper to call Supabase safely. When the user hasn't entered
// real Supabase credentials at build time, the helper shows a SnackBar
// asking them to add credentials in the Glassbox Backend tab and
// rebuild — the rest of the app keeps working.
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../config/supabase_config.dart';
import '../main.dart' show rootMessengerKey;

abstract class SupabaseHelper {
  SupabaseHelper._();

  /// True iff real Supabase credentials were entered at build time.
  static bool get isReady => SupabaseConfig.isConfigured;

  /// Convenience accessor — same as Supabase.instance.client. Always
  /// non-null after main()'s init (even with placeholder credentials),
  /// so existing code that does `Supabase.instance.client` keeps
  /// working. Use [safe] instead for any actual data call.
  static SupabaseClient get client => Supabase.instance.client;

  /// Shows a SnackBar telling the user to add Supabase credentials in
  /// the Glassbox Backend tab. Falls back to the global messenger when
  /// no widget [context] is available (e.g. from a fire-and-forget
  /// Future error handler).
  static void showNotReadyToast(BuildContext? context, {String? feature}) {
    final headline = (feature != null && feature.isNotEmpty)
        ? '$feature needs Supabase'
        : "Supabase isn't configured";
    final messenger = (context != null && context.mounted)
        ? ScaffoldMessenger.maybeOf(context)
        : null;
    final target = messenger ?? rootMessengerKey.currentState;
    if (target == null) return;
    target
      ..clearSnackBars()
      ..showSnackBar(SnackBar(
        content: Text(
          '$headline. Open this project in Glassbox → Backend tab, '
          'add your Supabase URL + anon key, then rebuild.',
        ),
        duration: const Duration(seconds: 5),
        behavior: SnackBarBehavior.floating,
      ));
  }

  /// Wraps a Supabase call. If credentials aren't configured, or the
  /// underlying call throws (network unreachable, table missing, etc.),
  /// shows a toast via [showNotReadyToast] and returns null. The caller
  /// can branch on null to render an empty-state instead of crashing.
  ///
  /// Usage:
  ///   final tracks = await SupabaseHelper.safe(context, () async =>
  ///     SupabaseHelper.client.from('tracks').select(),
  ///     feature: 'Library');
  static Future<T?> safe<T>(
    BuildContext? context,
    Future<T> Function() op, {
    String? feature,
  }) async {
    if (!isReady) {
      showNotReadyToast(context, feature: feature);
      return null;
    }
    try {
      return await op();
    } catch (e, st) {
      debugPrint('SupabaseHelper.safe failed: $e\n$st');
      showNotReadyToast(context, feature: feature);
      return null;
    }
  }
}
